### ISSUE TITLE
DB - Create game file insert template data

### ISSUE THREAD

**Issue by idaka123** [idaka123/GameStore-API#8]
Hi @FOX2920 

Task: 
- Update a template insert game data for table Games

you can use chat GPT getting the game data then review the game data to insert into the sql file

**Comment by FOX2920** [comment]
I have just finished inserting data of some random games into Games table.
https://docs.google.com/document/d/10V1Q3UApKzcgophl3ZhIHWkqG95LahsclY8dEV4ZXlY/edit?usp=sharing
Please let me know if there's anything wrong.
Thanks

**Comment by idaka123** [comment]
Hi @FOX2920  
Thanks for your data.

I have setup the store file in the below link
Could you take a look on this, we will process like this to initialize the database faster for the first time run for everyone

https://drive.google.com/drive/u/0/folders/1T6XTW9_0wM53QIQtz9yTKtvDrj-tLLoW?
fbclid=IwAR1Oqix_FcQUgJvylYkZNtQZ2dWK_7C2YR1JDIXUE_FQUJCC6Mcwy54ucP4

Thanks

**Comment by FOX2920** [comment]
I just created a MySQL database for the team.
To access it, open MySQL Workbench and click on the "+" sign to set up a new connection.
Enter the provided information on the screen (you can choose any name for the Connection name):

![Screenshot_79](https://user-images.githubusercontent.com/91709267/234359730-ace404d3-140e-459a-ab84-e70f18990081.png)

Hostname: database.cvjkjhwj5dws.ap-southeast-1.rds.amazonaws.com
Username: newuser
Password: 00000000

**NOTE: This user account is currently only authorized to execute select commands and cannot execute other commands.**

**Comment by idaka123** [comment]
lgtm, nice @FOX2920 
We will use this for production, meanwhile in we still keep using local database for development at staging

I will close this task
